"""Два новых поля в модели User

Revision ID: 759b88ad3103
Revises: 66b54f934fbe
Create Date: 2025-05-22 15:06:11.296044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759b88ad3103'
down_revision = '66b54f934fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
